export interface Country {
  iso3: string;
  nameEn: string;
  nameSk: string;
  eu: boolean;
  vatCode: string;
}

export const COUNTRIES: Country[] = [
  { iso3: "AFG", nameEn: "Afghanistan", nameSk: "Afganistan", eu: false, vatCode: "AF" },
  { iso3: "ALB", nameEn: "Albania", nameSk: "Albánsko", eu: false, vatCode: "AL" },
  { iso3: "ATA", nameEn: "Antarctica", nameSk: "Antarktída", eu: false, vatCode: "AQ" },
  { iso3: "DZA", nameEn: "Algeria", nameSk: "Alžírsko", eu: false, vatCode: "DZ" },
  { iso3: "ASM", nameEn: "American Samoa", nameSk: "Americká Samoa", eu: false, vatCode: "AS" },
  { iso3: "AND", nameEn: "Andorra", nameSk: "Andorra", eu: false, vatCode: "AD" },
  { iso3: "AGO", nameEn: "Angola", nameSk: "Angola", eu: false, vatCode: "AO" },
  { iso3: "ATG", nameEn: "Antigua & Barbuda", nameSk: "Antigua a Barbuda", eu: false, vatCode: "AG" },
  { iso3: "AZE", nameEn: "Azerbaijan", nameSk: "Azerbajdžan", eu: false, vatCode: "AZ" },
  { iso3: "ARG", nameEn: "Argentina", nameSk: "Argentína", eu: false, vatCode: "AR" },
  { iso3: "AUS", nameEn: "Australia", nameSk: "Austrália", eu: false, vatCode: "AU" },
  { iso3: "BHS", nameEn: "Bahamas", nameSk: "Bahamy", eu: false, vatCode: "BS" },
  { iso3: "BHR", nameEn: "Bahrain", nameSk: "Bahrajn", eu: false, vatCode: "BH" },
  { iso3: "BGD", nameEn: "Bangladesh", nameSk: "Bangladéš", eu: false, vatCode: "BD" },
  { iso3: "ARM", nameEn: "Armenia", nameSk: "Arménsko", eu: false, vatCode: "AM" },
  { iso3: "BRB", nameEn: "Barbados", nameSk: "Barbados", eu: false, vatCode: "BB" },
  { iso3: "BMU", nameEn: "Bermuda", nameSk: "Bermudy", eu: false, vatCode: "BM" },
  { iso3: "BTN", nameEn: "Bhutan", nameSk: "Bhután", eu: false, vatCode: "BT" },
  { iso3: "BOL", nameEn: "Bolivia", nameSk: "Bolívia", eu: false, vatCode: "BO" },
  { iso3: "BIH", nameEn: "Bosnia & Herzegovina", nameSk: "Bosna a Hercegovina", eu: false, vatCode: "BA" },
  { iso3: "BWA", nameEn: "Botswana", nameSk: "Botswana", eu: false, vatCode: "BW" },
  { iso3: "BVT", nameEn: "Bouvet Island", nameSk: "Bouvetov ostrov", eu: false, vatCode: "BV" },
  { iso3: "BRA", nameEn: "Brazil", nameSk: "Brazília", eu: false, vatCode: "BR" },
  { iso3: "BLZ", nameEn: "Belize", nameSk: "Belize", eu: false, vatCode: "BZ" },
  { iso3: "IOT", nameEn: "British Indian Ocean Territory", nameSk: "Britské indickooceánske územie", eu: false, vatCode: "IO" },
  { iso3: "SLB", nameEn: "Solomon Islands", nameSk: "Šalamúnove ostrovy", eu: false, vatCode: "SB" },
  { iso3: "VGB", nameEn: "British Virgin Islands", nameSk: "Britské Panenské ostrovy", eu: false, vatCode: "VG" },
  { iso3: "BRN", nameEn: "Brunei", nameSk: "Brunej", eu: false, vatCode: "BN" },
  { iso3: "BGR", nameEn: "Bulgaria", nameSk: "Bulharsko", eu: true, vatCode: "BG" },
  { iso3: "MMR", nameEn: "Myanmar (Burma)", nameSk: "Mjanmarsko", eu: false, vatCode: "MM" },
  { iso3: "BDI", nameEn: "Burundi", nameSk: "Burundi", eu: false, vatCode: "BI" },
  { iso3: "BLR", nameEn: "Belarus", nameSk: "Bielorusko", eu: false, vatCode: "BY" },
  { iso3: "KHM", nameEn: "Cambodia", nameSk: "Kambodža", eu: false, vatCode: "KH" },
  { iso3: "CMR", nameEn: "Cameroon", nameSk: "Kamerun", eu: false, vatCode: "CM" },
  { iso3: "CAN", nameEn: "Canada", nameSk: "Kanada", eu: false, vatCode: "CA" },
  { iso3: "CPV", nameEn: "Cape Verde", nameSk: "Kapverdy", eu: false, vatCode: "CV" },
  { iso3: "CYM", nameEn: "Cayman Islands", nameSk: "Kajmanie ostrovy", eu: false, vatCode: "KY" },
  { iso3: "CAF", nameEn: "Central African Republic", nameSk: "Stredoafrická republika", eu: false, vatCode: "CF" },
  { iso3: "LKA", nameEn: "Sri Lanka", nameSk: "Srí Lanka", eu: false, vatCode: "LK" },
  { iso3: "TCD", nameEn: "Chad", nameSk: "Čad", eu: false, vatCode: "TD" },
  { iso3: "CHL", nameEn: "Chile", nameSk: "Čile", eu: false, vatCode: "CL" },
  { iso3: "TWN", nameEn: "Taiwan", nameSk: "Taiwan", eu: false, vatCode: "TW" },
  { iso3: "CXR", nameEn: "Christmas Island", nameSk: "Vianočný ostrov", eu: false, vatCode: "CX" },
  { iso3: "CCK", nameEn: "Cocos (Keeling) Islands", nameSk: "Kokosové ostrovy", eu: false, vatCode: "CC" },
  { iso3: "COL", nameEn: "Colombia", nameSk: "Kolumbia", eu: false, vatCode: "CO" },
  { iso3: "COM", nameEn: "Comoros", nameSk: "Komory", eu: false, vatCode: "KM" },
  { iso3: "MYT", nameEn: "Mayotte", nameSk: "Mayotte", eu: false, vatCode: "YT" },
  { iso3: "COG", nameEn: "Republic of the Congo", nameSk: "Kongo", eu: false, vatCode: "CG" },
  { iso3: "COD", nameEn: "DR Congo", nameSk: "Konžská demokratická republika", eu: false, vatCode: "CD" },
  { iso3: "COK", nameEn: "Cook Islands", nameSk: "Cookove ostrovy", eu: false, vatCode: "CK" },
  { iso3: "HRV", nameEn: "Croatia", nameSk: "Chorvátsko", eu: true, vatCode: "HR" },
  { iso3: "CUB", nameEn: "Cuba", nameSk: "Kuba", eu: false, vatCode: "CU" },
  { iso3: "CYP", nameEn: "Cyprus", nameSk: "Cyprus", eu: true, vatCode: "CY" },
  { iso3: "DNK", nameEn: "Denmark", nameSk: "Dánsko", eu: true, vatCode: "DK" },
  { iso3: "DJI", nameEn: "Djibouti", nameSk: "Džibuti", eu: false, vatCode: "DJ" },
  { iso3: "DMA", nameEn: "Dominica", nameSk: "Dominika", eu: false, vatCode: "DM" },
  { iso3: "DOM", nameEn: "Dominican Republic", nameSk: "Dominikánska republika", eu: false, vatCode: "DO" },
  { iso3: "ECU", nameEn: "Ecuador", nameSk: "Ekvádor", eu: false, vatCode: "EC" },
  { iso3: "SLV", nameEn: "El Salvador", nameSk: "Salvádor", eu: false, vatCode: "SV" },
  { iso3: "GNQ", nameEn: "Equatorial Guinea", nameSk: "Rovníková Guinea", eu: false, vatCode: "GQ" },
  { iso3: "ETH", nameEn: "Ethiopia", nameSk: "Etiópia", eu: false, vatCode: "ET" },
  { iso3: "ERI", nameEn: "Eritrea", nameSk: "Eritrea", eu: false, vatCode: "ER" },
  { iso3: "EST", nameEn: "Estonia", nameSk: "Estónsko", eu: true, vatCode: "EE" },
  { iso3: "FRO", nameEn: "Faroe Islands", nameSk: "Faerské ostrovy", eu: false, vatCode: "FO" },
  { iso3: "FLK", nameEn: "Falkland Islands", nameSk: "Falklandské ostrovy", eu: false, vatCode: "FK" },
  { iso3: "SGS", nameEn: "South Georgia & South Sandwich Islands", nameSk: "Južná Georgia a Južné Sandwichove ostrovy", eu: false, vatCode: "GS" },
  { iso3: "FJI", nameEn: "Fiji", nameSk: "Fidži", eu: false, vatCode: "FJ" },
  { iso3: "FIN", nameEn: "Finland", nameSk: "Fínsko", eu: true, vatCode: "FI" },
  { iso3: "ALA", nameEn: "Aland Islands", nameSk: "Alandy", eu: false, vatCode: "AX" },
  { iso3: "GUF", nameEn: "French Guiana", nameSk: "Francúzska Guyana", eu: false, vatCode: "GF" },
  { iso3: "PYF", nameEn: "French Polynesia", nameSk: "Francúzska Polynézia", eu: false, vatCode: "PF" },
  { iso3: "ATF", nameEn: "French Southern Territories", nameSk: "Francúzske južné územia", eu: false, vatCode: "TF" },
  { iso3: "GAB", nameEn: "Gabon", nameSk: "Gabon", eu: false, vatCode: "GA" },
  { iso3: "GMB", nameEn: "Gambia", nameSk: "Gambia", eu: false, vatCode: "GM" },
  { iso3: "GEO", nameEn: "Georgia", nameSk: "Gruzínsko", eu: false, vatCode: "GE" },
  { iso3: "GHA", nameEn: "Ghana", nameSk: "Ghana", eu: false, vatCode: "GH" },
  { iso3: "GIB", nameEn: "Gibraltar", nameSk: "Gibraltár", eu: false, vatCode: "GI" },
  { iso3: "KIR", nameEn: "Kiribati", nameSk: "Kiribati", eu: false, vatCode: "KI" },
  { iso3: "GTM", nameEn: "Guatemala", nameSk: "Guatemala", eu: false, vatCode: "GT" },
  { iso3: "GIN", nameEn: "Guinea", nameSk: "Guinea", eu: false, vatCode: "GN" },
  { iso3: "GNB", nameEn: "Guinea-Bissau", nameSk: "Guinea-Bissau", eu: false, vatCode: "GW" },
  { iso3: "GUY", nameEn: "Guyana", nameSk: "Guyana", eu: false, vatCode: "GY" },
  { iso3: "HTI", nameEn: "Haiti", nameSk: "Haiti", eu: false, vatCode: "HT" },
  { iso3: "HMD", nameEn: "Heard & McDonald Islands", nameSk: "Heardov ostrov a McDonaldove ostrovy", eu: false, vatCode: "HM" },
  { iso3: "VAT", nameEn: "Vatican City", nameSk: "Vatikán", eu: false, vatCode: "VA" },
  { iso3: "HND", nameEn: "Honduras", nameSk: "Honduras", eu: false, vatCode: "HN" },
  { iso3: "HKG", nameEn: "Hong Kong", nameSk: "Hongkong", eu: false, vatCode: "HK" },
  { iso3: "ISL", nameEn: "Iceland", nameSk: "Island", eu: false, vatCode: "IS" },
  { iso3: "IND", nameEn: "India", nameSk: "India", eu: false, vatCode: "IN" },
  { iso3: "IDN", nameEn: "Indonesia", nameSk: "Indonézia", eu: false, vatCode: "ID" },
  { iso3: "IRN", nameEn: "Iran", nameSk: "Irán", eu: false, vatCode: "IR" },
  { iso3: "IRQ", nameEn: "Iraq", nameSk: "Irak", eu: false, vatCode: "IQ" },
  { iso3: "IRL", nameEn: "Ireland", nameSk: "Írsko", eu: true, vatCode: "IE" },
  { iso3: "ISR", nameEn: "Israel", nameSk: "Izrael", eu: false, vatCode: "IL" },
  { iso3: "JAM", nameEn: "Jamaica", nameSk: "Jamajka", eu: false, vatCode: "JM" },
  { iso3: "JPN", nameEn: "Japan", nameSk: "Japonsko", eu: false, vatCode: "JP" },
  { iso3: "KAZ", nameEn: "Kazakhstan", nameSk: "Kazachstan", eu: false, vatCode: "KZ" },
  { iso3: "JOR", nameEn: "Jordan", nameSk: "Jordánsko", eu: false, vatCode: "JO" },
  { iso3: "KEN", nameEn: "Kenya", nameSk: "Keňa", eu: false, vatCode: "KE" },
  { iso3: "PRK", nameEn: "North Korea", nameSk: "Severná Kórea", eu: false, vatCode: "KP" },
  { iso3: "KOR", nameEn: "South Korea", nameSk: "Južná Kórea", eu: false, vatCode: "KR" },
  { iso3: "KWT", nameEn: "Kuwait", nameSk: "Kuvajt", eu: false, vatCode: "KW" },
  { iso3: "KGZ", nameEn: "Kyrgyzstan", nameSk: "Kirgizsko", eu: false, vatCode: "KG" },
  { iso3: "LAO", nameEn: "Laos", nameSk: "Laos", eu: false, vatCode: "LA" },
  { iso3: "LBN", nameEn: "Lebanon", nameSk: "Libanon", eu: false, vatCode: "LB" },
  { iso3: "LSO", nameEn: "Lesotho", nameSk: "Lesotho", eu: false, vatCode: "LS" },
  { iso3: "LVA", nameEn: "Latvia", nameSk: "Lotyšsko", eu: true, vatCode: "LV" },
  { iso3: "LBR", nameEn: "Liberia", nameSk: "Libéria", eu: false, vatCode: "LR" },
  { iso3: "LBY", nameEn: "Libya", nameSk: "Líbya", eu: false, vatCode: "LY" },
  { iso3: "LIE", nameEn: "Liechtenstein", nameSk: "Lichtenštajnsko", eu: false, vatCode: "LI" },
  { iso3: "LTU", nameEn: "Lithuania", nameSk: "Litva", eu: true, vatCode: "LT" },
  { iso3: "LUX", nameEn: "Luxembourg", nameSk: "Luxembursko", eu: true, vatCode: "LU" },
  { iso3: "MAC", nameEn: "Macao", nameSk: "Macao", eu: false, vatCode: "MO" },
  { iso3: "MDG", nameEn: "Madagascar", nameSk: "Madagaskar", eu: false, vatCode: "MG" },
  { iso3: "MWI", nameEn: "Malawi", nameSk: "Malawi", eu: false, vatCode: "MW" },
  { iso3: "MYS", nameEn: "Malaysia", nameSk: "Malajzia", eu: false, vatCode: "MY" },
  { iso3: "MDV", nameEn: "Maldives", nameSk: "Maldivy", eu: false, vatCode: "MV" },
  { iso3: "MLI", nameEn: "Mali", nameSk: "Mali", eu: false, vatCode: "ML" },
  { iso3: "MLT", nameEn: "Malta", nameSk: "Malta", eu: true, vatCode: "MT" },
  { iso3: "MTQ", nameEn: "Martinique", nameSk: "Martinik", eu: false, vatCode: "MQ" },
  { iso3: "MRT", nameEn: "Mauritania", nameSk: "Mauritánia", eu: false, vatCode: "MR" },
  { iso3: "MUS", nameEn: "Mauritius", nameSk: "Maurícius", eu: false, vatCode: "MU" },
  { iso3: "MEX", nameEn: "Mexico", nameSk: "Mexiko", eu: false, vatCode: "MX" },
  { iso3: "MCO", nameEn: "Monaco", nameSk: "Monako", eu: false, vatCode: "MC" },
  { iso3: "MNG", nameEn: "Mongolia", nameSk: "Mongolsko", eu: false, vatCode: "MN" },
  { iso3: "MDA", nameEn: "Moldova", nameSk: "Moldavsko", eu: false, vatCode: "MD" },
  { iso3: "MNE", nameEn: "Montenegro", nameSk: "Čierna Hora", eu: false, vatCode: "ME" },
  { iso3: "MSR", nameEn: "Montserrat", nameSk: "Montserrat", eu: false, vatCode: "MS" },
  { iso3: "MAR", nameEn: "Morocco", nameSk: "Maroko", eu: false, vatCode: "MA" },
  { iso3: "MOZ", nameEn: "Mozambique", nameSk: "Mozambik", eu: false, vatCode: "MZ" },
  { iso3: "NAM", nameEn: "Namibia", nameSk: "Namíbia", eu: false, vatCode: "NA" },
  { iso3: "NRU", nameEn: "Nauru", nameSk: "Nauru", eu: false, vatCode: "NR" },
  { iso3: "NPL", nameEn: "Nepal", nameSk: "Nepál", eu: false, vatCode: "NP" },
  { iso3: "NLD", nameEn: "Netherlands", nameSk: "Holandsko", eu: true, vatCode: "NL" },
  { iso3: "ANT", nameEn: "Netherlands Antilles", nameSk: "Holandské Antily", eu: false, vatCode: "AN" },
  { iso3: "NCL", nameEn: "New Caledonia", nameSk: "Nová Kaledónia", eu: false, vatCode: "NC" },
  { iso3: "VUT", nameEn: "Vanuatu", nameSk: "Vanuatu", eu: false, vatCode: "VU" },
  { iso3: "NZL", nameEn: "New Zealand", nameSk: "Nový Zéland", eu: false, vatCode: "NZ" },
  { iso3: "NIC", nameEn: "Nicaragua", nameSk: "Nikaragua", eu: false, vatCode: "NI" },
  { iso3: "NER", nameEn: "Niger", nameSk: "Niger", eu: false, vatCode: "NE" },
  { iso3: "NGA", nameEn: "Nigeria", nameSk: "Nigéria", eu: false, vatCode: "NG" },
  { iso3: "NIU", nameEn: "Niue", nameSk: "Niue", eu: false, vatCode: "NU" },
  { iso3: "NFK", nameEn: "Norfolk Island", nameSk: "Norfolkov ostrov", eu: false, vatCode: "NF" },
  { iso3: "NOR", nameEn: "Norway", nameSk: "Nórsko", eu: false, vatCode: "NO" },
  { iso3: "MNP", nameEn: "Northern Mariana Islands", nameSk: "Severné Mariánske ostrovy", eu: false, vatCode: "MP" },
  { iso3: "UMI", nameEn: "U.S. Minor Outlying Islands", nameSk: "Menšie odľahlé ostrovy USA", eu: false, vatCode: "UM" },
  { iso3: "FSM", nameEn: "Micronesia", nameSk: "Mikronézia", eu: false, vatCode: "FM" },
  { iso3: "MHL", nameEn: "Marshall Islands", nameSk: "Marshallove ostrovy", eu: false, vatCode: "MH" },
  { iso3: "PLW", nameEn: "Palau", nameSk: "Palau", eu: false, vatCode: "PW" },
  { iso3: "PAK", nameEn: "Pakistan", nameSk: "Pakistan", eu: false, vatCode: "PK" },
  { iso3: "PAN", nameEn: "Panama", nameSk: "Panama", eu: false, vatCode: "PA" },
  { iso3: "PNG", nameEn: "Papua New Guinea", nameSk: "Papua-Nová Guinea", eu: false, vatCode: "PG" },
  { iso3: "PRY", nameEn: "Paraguay", nameSk: "Paraguaj", eu: false, vatCode: "PY" },
  { iso3: "PER", nameEn: "Peru", nameSk: "Peru", eu: false, vatCode: "PE" },
  { iso3: "PHL", nameEn: "Philippines", nameSk: "Filipíny", eu: false, vatCode: "PH" },
  { iso3: "PCN", nameEn: "Pitcairn Islands", nameSk: "Pitcairnove ostrovy", eu: false, vatCode: "PN" },
  { iso3: "PRT", nameEn: "Portugal", nameSk: "Portugalsko", eu: true, vatCode: "PT" },
  { iso3: "GNQ", nameEn: "Equatorial Guinea", nameSk: "Rovníková Guinea", eu: false, vatCode: "GQ" },
  { iso3: "QAT", nameEn: "Qatar", nameSk: "Katar", eu: false, vatCode: "QA" },
  { iso3: "REU", nameEn: "Réunion", nameSk: "Réunion", eu: false, vatCode: "RE" },
  { iso3: "ROU", nameEn: "Romania", nameSk: "Rumunsko", eu: true, vatCode: "RO" },
  { iso3: "RWA", nameEn: "Rwanda", nameSk: "Rwanda", eu: false, vatCode: "RW" },
  { iso3: "SHN", nameEn: "St. Helena", nameSk: "Svätá Helena", eu: false, vatCode: "SH" },
  { iso3: "KNA", nameEn: "St. Kitts & Nevis", nameSk: "Svätý Krištof a Nevis", eu: false, vatCode: "KN" },
  { iso3: "SPM", nameEn: "St. Pierre & Miquelon", nameSk: "Saint Pierre a Miquelon", eu: false, vatCode: "PM" },
  { iso3: "VCT", nameEn: "St. Vincent & Grenadines", nameSk: "Svätý Vincent a Grenadíny", eu: false, vatCode: "VC" },
  { iso3: "SMR", nameEn: "San Marino", nameSk: "San Maríno", eu: false, vatCode: "SM" },
  { iso3: "STP", nameEn: "Sao Tome & Principe", nameSk: "Svätý Tomáš a Princov ostrov", eu: false, vatCode: "ST" },
  { iso3: "SAU", nameEn: "Saudi Arabia", nameSk: "Saudská Arábia", eu: false, vatCode: "SA" },
  { iso3: "SEN", nameEn: "Senegal", nameSk: "Senegal", eu: false, vatCode: "SN" },
  { iso3: "SRB", nameEn: "Serbia", nameSk: "Srbsko", eu: false, vatCode: "RS" },
  { iso3: "SYC", nameEn: "Seychelles", nameSk: "Seychely", eu: false, vatCode: "SC" },
  { iso3: "SLE", nameEn: "Sierra Leone", nameSk: "Sierra Leone", eu: false, vatCode: "SL" },
  { iso3: "SGP", nameEn: "Singapore", nameSk: "Singapur", eu: false, vatCode: "SG" },
  { iso3: "SVK", nameEn: "Slovakia", nameSk: "Slovenská republika", eu: true, vatCode: "SK" },
  { iso3: "SVN", nameEn: "Slovenia", nameSk: "Slovinsko", eu: true, vatCode: "SI" },
  { iso3: "SOM", nameEn: "Somalia", nameSk: "Somálsko", eu: false, vatCode: "SO" },
  { iso3: "ZAF", nameEn: "South Africa", nameSk: "Juhoafrická republika", eu: false, vatCode: "ZA" },
  { iso3: "SDN", nameEn: "Sudan", nameSk: "Sudán", eu: false, vatCode: "SD" },
  { iso3: "SSD", nameEn: "South Sudan", nameSk: "Južný Sudán", eu: false, vatCode: "SS" },
  { iso3: "SUR", nameEn: "Suriname", nameSk: "Surinam", eu: false, vatCode: "SR" },
  { iso3: "SJM", nameEn: "Svalbard & Jan Mayen", nameSk: "Svalbard a Jan Mayen", eu: false, vatCode: "SJ" },
  { iso3: "SWZ", nameEn: "Eswatini", nameSk: "Svazijsko", eu: false, vatCode: "SZ" },
  { iso3: "SWE", nameEn: "Sweden", nameSk: "Švédsko", eu: true, vatCode: "SE" },
  { iso3: "CHE", nameEn: "Switzerland", nameSk: "Švajčiarsko", eu: false, vatCode: "CH" },
  { iso3: "SYR", nameEn: "Syria", nameSk: "Sýria", eu: false, vatCode: "SY" },
  { iso3: "TJK", nameEn: "Tajikistan", nameSk: "Tadžikistan", eu: false, vatCode: "TJ" },
  { iso3: "THA", nameEn: "Thailand", nameSk: "Thajsko", eu: false, vatCode: "TH" },
  { iso3: "TGO", nameEn: "Togo", nameSk: "Togo", eu: false, vatCode: "TG" },
  { iso3: "TKL", nameEn: "Tokelau", nameSk: "Tokelau", eu: false, vatCode: "TK" },
  { iso3: "TON", nameEn: "Tonga", nameSk: "Tonga", eu: false, vatCode: "TO" },
  { iso3: "TTO", nameEn: "Trinidad & Tobago", nameSk: "Trinidad a Tobago", eu: false, vatCode: "TT" },
  { iso3: "ARE", nameEn: "United Arab Emirates", nameSk: "Spojené arabské emiráty", eu: false, vatCode: "AE" },
  { iso3: "TUN", nameEn: "Tunisia", nameSk: "Tunisko", eu: false, vatCode: "TN" },
  { iso3: "TUR", nameEn: "Türkiye", nameSk: "Turecko", eu: false, vatCode: "TR" },
  { iso3: "TKM", nameEn: "Turkmenistan", nameSk: "Turkménsko", eu: false, vatCode: "TM" },
  { iso3: "TCA", nameEn: "Turks & Caicos Islands", nameSk: "Turks a Caicos", eu: false, vatCode: "TC" },
  { iso3: "TUV", nameEn: "Tuvalu", nameSk: "Tuvalu", eu: false, vatCode: "TV" },
  { iso3: "UGA", nameEn: "Uganda", nameSk: "Uganda", eu: false, vatCode: "UG" },
  { iso3: "MKD", nameEn: "North Macedonia", nameSk: "Macedónsko", eu: false, vatCode: "MK" },
  { iso3: "EGY", nameEn: "Egypt", nameSk: "Egypt", eu: false, vatCode: "EG" },
  { iso3: "GGY", nameEn: "Guernsey", nameSk: "Guernsey", eu: false, vatCode: "GG" },
  { iso3: "JEY", nameEn: "Jersey", nameSk: "Jersey", eu: false, vatCode: "JE" },
  { iso3: "IMN", nameEn: "Isle of Man", nameSk: "Man", eu: false, vatCode: "IM" },
  { iso3: "TZA", nameEn: "Tanzania", nameSk: "Tanzánia", eu: false, vatCode: "TZ" },
  { iso3: "VIR", nameEn: "U.S. Virgin Islands", nameSk: "Americké Panenské ostrovy", eu: false, vatCode: "VI" },
  { iso3: "BFA", nameEn: "Burkina Faso", nameSk: "Burkina Faso", eu: false, vatCode: "BF" },
  { iso3: "URY", nameEn: "Uruguay", nameSk: "Uruguaj", eu: false, vatCode: "UY" },
  { iso3: "UZB", nameEn: "Uzbekistan", nameSk: "Uzbekistan", eu: false, vatCode: "UZ" },
  { iso3: "VEN", nameEn: "Venezuela", nameSk: "Venezuela", eu: false, vatCode: "VE" },
  { iso3: "WLF", nameEn: "Wallis & Futuna", nameSk: "Wallis a Futuna", eu: false, vatCode: "WF" },
  { iso3: "WSM", nameEn: "Samoa", nameSk: "Samoa", eu: false, vatCode: "WS" },
  { iso3: "YEM", nameEn: "Yemen", nameSk: "Jemen", eu: false, vatCode: "YE" },
  { iso3: "ZMB", nameEn: "Zambia", nameSk: "Zambia", eu: false, vatCode: "ZM" },
  { iso3: "CHN", nameEn: "China", nameSk: "Čína", eu: false, vatCode: "CN" },
  { iso3: "RUS", nameEn: "Russia", nameSk: "Rusko", eu: false, vatCode: "RU" },
  { iso3: "USA", nameEn: "United States", nameSk: "Spojené štáty americké", eu: false, vatCode: "US" },
  { iso3: "UKR", nameEn: "Ukraine", nameSk: "Ukrajina", eu: false, vatCode: "UA" },
  { iso3: "CZE", nameEn: "Czechia", nameSk: "Česká republika", eu: true, vatCode: "CZ" },
  { iso3: "BEL", nameEn: "Belgium", nameSk: "Belgicko", eu: true, vatCode: "BE" },
  { iso3: "FRA", nameEn: "France", nameSk: "Francúzsko", eu: true, vatCode: "FR" },
  { iso3: "GRC", nameEn: "Greece", nameSk: "Grécko", eu: true, vatCode: "EL" },
  { iso3: "AUT", nameEn: "Austria", nameSk: "Rakúsko", eu: true, vatCode: "AT" },
  { iso3: "ESP", nameEn: "Spain", nameSk: "Španielsko", eu: true, vatCode: "ES" },
  { iso3: "ITA", nameEn: "Italy", nameSk: "Taliansko", eu: true, vatCode: "IT" },
  { iso3: "DEU", nameEn: "Germany", nameSk: "Nemecko", eu: true, vatCode: "DE" },
  { iso3: "GBR", nameEn: "United Kingdom", nameSk: "Spojené kráľovstvo", eu: false, vatCode: "GB" },
  { iso3: "HUN", nameEn: "Hungary", nameSk: "Maďarsko", eu: true, vatCode: "HU" },
  { iso3: "POL", nameEn: "Poland", nameSk: "Poľsko", eu: true, vatCode: "PL" },
];

/**
 * Build a lookup index: normalised string → Country.
 * Matches against iso3, nameEn, nameSk, vatCode (case-insensitive, trimmed).
 */
function buildIndex(): Map<string, Country> {
  const idx = new Map<string, Country>();
  const add = (key: string, c: Country) => {
    const k = key.trim().toLowerCase();
    if (k && !idx.has(k)) idx.set(k, c);
  };
  for (const c of COUNTRIES) {
    add(c.iso3, c);
    add(c.nameEn, c);
    add(c.nameSk, c);
    if (c.vatCode) add(c.vatCode, c);
  }
  return idx;
}

const COUNTRY_INDEX = buildIndex();

export type CountryFormat = "original" | "name_sk" | "name_en" | "iso3" | "vat_code";

/**
 * Lookup a country by any known representation and return the desired format.
 * Returns undefined when the value cannot be matched.
 */
export function lookupCountry(value: string, format: CountryFormat): string | undefined {
  if (!value) return undefined;
  const key = value.trim().toLowerCase();
  const country = COUNTRY_INDEX.get(key);
  if (!country) return undefined;
  switch (format) {
    case "name_sk":  return country.nameSk;
    case "name_en":  return country.nameEn;
    case "iso3":     return country.iso3;
    case "vat_code": return country.vatCode || undefined;
    default:         return undefined;
  }
}

export const COUNTRY_FIELD_KEYWORDS = [
  "country", "krajin", "zem", "stat", "land", "nation",
  "origin", "povodenie", "povodenia", "pochadza",
  "CountryOfOrigin", "country_of_origin", "vyrobn",
];
